<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../GiftEntry.cs" Link="GiftEntry.cs" />
    <Compile Include="../../GiftLedger.cs" Link="GiftLedger.cs" />
  </ItemGroup>
</Project>
